// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/buscar-clientes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "No autenticado." }],
    isError: true
  };
}
function toResult(data, error) {
  if (error) {
    return { content: [{ type: "text", text: error.message }], isError: true };
  }
  return {
    content: [{ type: "text", text: JSON.stringify(data ?? []) }],
    structuredContent: { rows: data ?? [] }
  };
}

// src/lib/mcp/tools/buscar-clientes.ts
var buscar_clientes_default = defineTool({
  name: "buscar_clientes",
  title: "Buscar clientes",
  description: "Busca clientes por raz\xF3n social, c\xF3digo o documento. Devuelve datos de contacto, tipo de cliente y estado.",
  inputSchema: {
    query: z.string().describe("Texto a buscar en raz\xF3n social, c\xF3digo o nombre de persona natural.").optional(),
    limite: z.number().int().describe("M\xE1ximo de resultados (por defecto 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limite }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("clientes").select(
      "id, codigo, razon_social, nombre_persona_natural, tipo_cliente, email, telefono, activo, sector, regimen_tributario"
    ).order("razon_social").limit(Math.min(limite ?? 20, 100));
    if (query?.trim()) {
      const t = query.trim();
      q = q.or(
        `razon_social.ilike.%${t}%,codigo.ilike.%${t}%,nombre_persona_natural.ilike.%${t}%`
      );
    }
    const { data, error } = await q;
    return toResult(data, error);
  }
});

// src/lib/mcp/tools/listar-contratos.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var listar_contratos_default = defineTool2({
  name: "listar_contratos",
  title: "Listar contratos",
  description: "Lista contratos con su cliente, estado, condici\xF3n, montos y vigencia. Permite filtrar por estado o por texto del n\xFAmero/descripci\xF3n.",
  inputSchema: {
    estado: z2.string().describe("Estado del contrato, por ejemplo 'activo'.").optional(),
    query: z2.string().describe("Texto a buscar en n\xFAmero o descripci\xF3n del contrato.").optional(),
    limite: z2.number().int().describe("M\xE1ximo de resultados (por defecto 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ estado, query, limite }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("contratos").select(
      "id, numero, descripcion, tipo_servicio, status, condicion, moneda, monto_mensual, monto_total, fecha_inicio, fecha_fin, clientes(razon_social, codigo)"
    ).order("fecha_inicio", { ascending: false }).limit(Math.min(limite ?? 20, 100));
    if (estado?.trim()) q = q.eq("status", estado.trim());
    if (query?.trim()) {
      const t = query.trim();
      q = q.or(`numero.ilike.%${t}%,descripcion.ilike.%${t}%`);
    }
    const { data, error } = await q;
    return toResult(data, error);
  }
});

// src/lib/mcp/tools/listar-proformas.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var listar_proformas_default = defineTool3({
  name: "listar_proformas",
  title: "Listar proformas",
  description: "Lista proformas con cliente, estado, fechas de emisi\xF3n/vencimiento y montos (subtotal, IGV, total).",
  inputSchema: {
    estado: z3.string().describe("Estado de la proforma, por ejemplo 'pendiente'.").optional(),
    desde: z3.string().describe("Fecha m\xEDnima de emisi\xF3n en formato YYYY-MM-DD.").optional(),
    hasta: z3.string().describe("Fecha m\xE1xima de emisi\xF3n en formato YYYY-MM-DD.").optional(),
    limite: z3.number().int().describe("M\xE1ximo de resultados (por defecto 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ estado, desde, hasta, limite }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("proformas").select(
      "id, numero, tipo, status, moneda, subtotal, igv, total, fecha_emision, fecha_vencimiento, clientes(razon_social, codigo)"
    ).order("fecha_emision", { ascending: false }).limit(Math.min(limite ?? 20, 100));
    if (estado?.trim()) q = q.eq("status", estado.trim());
    if (desde?.trim()) q = q.gte("fecha_emision", desde.trim());
    if (hasta?.trim()) q = q.lte("fecha_emision", hasta.trim());
    const { data, error } = await q;
    return toResult(data, error);
  }
});

// src/lib/mcp/tools/listar-pagos.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var listar_pagos_default = defineTool4({
  name: "listar_pagos",
  title: "Listar pagos",
  description: "Lista cuotas y pagos de contratos con su estado, monto, fecha de vencimiento y fecha de pago. \xDAtil para revisar cobranzas pendientes o vencidas.",
  inputSchema: {
    estado: z4.string().describe("Estado del pago, por ejemplo 'pendiente' o 'pagado'.").optional(),
    vence_desde: z4.string().describe("Fecha m\xEDnima de vencimiento en formato YYYY-MM-DD.").optional(),
    vence_hasta: z4.string().describe("Fecha m\xE1xima de vencimiento en formato YYYY-MM-DD.").optional(),
    limite: z4.number().int().describe("M\xE1ximo de resultados (por defecto 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ estado, vence_desde, vence_hasta, limite }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("pagos").select(
      "id, monto, monto_neto, status, fecha_vencimiento, fecha_pago, metodo_pago, numero_comprobante, contratos(numero, clientes(razon_social))"
    ).order("fecha_vencimiento", { ascending: true }).limit(Math.min(limite ?? 20, 100));
    if (estado?.trim()) q = q.eq("status", estado.trim());
    if (vence_desde?.trim()) q = q.gte("fecha_vencimiento", vence_desde.trim());
    if (vence_hasta?.trim()) q = q.lte("fecha_vencimiento", vence_hasta.trim());
    const { data, error } = await q;
    return toResult(data, error);
  }
});

// src/lib/mcp/tools/listar-egresos.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^3.25.76";
var listar_egresos_default = defineTool5({
  name: "listar_egresos",
  title: "Listar egresos",
  description: "Lista egresos con su c\xF3digo, proveedor, categor\xEDa, estado, m\xE9todo de pago y montos, filtrables por estado y rango de fechas.",
  inputSchema: {
    estado: z5.string().describe("Estado del egreso: borrador, pendiente, aprobado, rechazado, pagado o anulado.").optional(),
    desde: z5.string().describe("Fecha m\xEDnima del egreso en formato YYYY-MM-DD.").optional(),
    hasta: z5.string().describe("Fecha m\xE1xima del egreso en formato YYYY-MM-DD.").optional(),
    limite: z5.number().int().describe("M\xE1ximo de resultados (por defecto 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ estado, desde, hasta, limite }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("expenses").select(
      "id, codigo, fecha_egreso, estado, moneda, subtotal, igv, total, proveedor_nombre, proveedor_documento, metodo_pago, centro_costo, descripcion, expense_categories(nombre)"
    ).order("fecha_egreso", { ascending: false }).limit(Math.min(limite ?? 20, 100));
    if (estado?.trim()) q = q.eq("estado", estado.trim());
    if (desde?.trim()) q = q.gte("fecha_egreso", desde.trim());
    if (hasta?.trim()) q = q.lte("fecha_egreso", hasta.trim());
    const { data, error } = await q;
    return toResult(data, error);
  }
});

// src/lib/mcp/tools/resumen-caja.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z6 } from "npm:zod@^3.25.76";
var resumen_caja_default = defineTool6({
  name: "resumen_caja",
  title: "Resumen de caja",
  description: "Calcula ingresos cobrados, egresos pagados y saldo del periodo indicado (por defecto el mes en curso).",
  inputSchema: {
    desde: z6.string().describe("Fecha inicial en formato YYYY-MM-DD.").optional(),
    hasta: z6.string().describe("Fecha final en formato YYYY-MM-DD.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ desde, hasta }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const now = /* @__PURE__ */ new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const first = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-01`;
    const last = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(
      new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate()
    )}`;
    const from = desde?.trim() || first;
    const to = hasta?.trim() || last;
    const supabase = supabaseForUser(ctx);
    const [ingresos, egresos] = await Promise.all([
      supabase.from("pagos").select("monto").eq("status", "pagado").gte("fecha_pago", from).lte("fecha_pago", to),
      supabase.from("expenses").select("total").eq("estado", "pagado").gte("fecha_egreso", from).lte("fecha_egreso", to)
    ]);
    const err = ingresos.error ?? egresos.error;
    if (err) return { content: [{ type: "text", text: err.message }], isError: true };
    const totalIngresos = (ingresos.data ?? []).reduce((s, r) => s + Number(r.monto ?? 0), 0);
    const totalEgresos = (egresos.data ?? []).reduce((s, r) => s + Number(r.total ?? 0), 0);
    const resumen = {
      desde: from,
      hasta: to,
      total_ingresos: totalIngresos,
      total_egresos: totalEgresos,
      saldo: totalIngresos - totalEgresos,
      cantidad_ingresos: ingresos.data?.length ?? 0,
      cantidad_egresos: egresos.data?.length ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(resumen) }],
      structuredContent: resumen
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mnrassdxhwykmldzubzr";
var mcp_default = defineMcp({
  name: "studioflow-pro",
  title: "StudioFlow Pro",
  version: "0.1.0",
  instructions: "Herramientas de solo lectura sobre el sistema contable: clientes, contratos, proformas, pagos, egresos y resumen de caja. Todas las consultas se ejecutan con los permisos del usuario autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    buscar_clientes_default,
    listar_contratos_default,
    listar_proformas_default,
    listar_pagos_default,
    listar_egresos_default,
    resumen_caja_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
